source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Notificator_Example', :exclusive => true do
  pod "Notificator", :path => "../"
end

target 'Notificator_Tests', :exclusive => true do
  pod "Notificator", :path => "../"

  
end
